name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        SOURCE: "./"
        REMOTE_HOST: "ec2-54-152-90-96.compute-1.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user"
        EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"
    
    - name: Add Plate Recognizer Key
      run: export PLATE_RECOGNIZER_KEY=${{ secrets.PLATE_RECOGNIZER_KEY }}
      env:
        PLATE_RECOGNIZER_KEY: ${{ secrets.PLATE_RECOGNIZER_KEY }}
